import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import style from './page.module.css'
import Link from 'next/link'
import Nav from './_component/Nav'
import SearchForm from './_component/SearchForm'
const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={style.wrap}>
          <header className={style.header}>
            <div className={style.logo_search_group}>
              <h1 className={style.logo}>
                <Link href={'/home'}>
                  <img src="/seul_logo.png" alt="seulg VM logo" />
                </Link>
              </h1>
              <Nav />
              <SearchForm />
            </div>
          </header>
          <main className={style.main}>{children}</main>
        </div>
      </body>
    </html>
  )
}
